url: http://google.com
browser: firefox # android, chrome, firefox, htmlunit, internet explorer, iPhone, iPad, opera, safari
window size: maximize # width x height EXP. 800x600 or maximize
implicitly wait: 10 # seconds

selenium server:
  url: localhost
  port: 4444
