url: http://google.com
browser: firefox # android, chrome, firefox, htmlunit, internet explorer, iPhone, iPad, opera, safari
window size: maximize # widthxheight or maximize

selenium server:
 url: localhost
 port: 4444
